// Figma Plugin Script - Generated by AI Design Workflow
// Run this in Figma: Plugins -> Development -> New Plugin -> Paste code

const CONFIG = {
    fileKey: "placeholder",
    token: "figd_placeholder...",
    stylePrefix: "Design Tokens/"
};

function notify(msg) {
    console.log(msg);
    figma.notify(msg);
}

function oklchToRgb(oklchStr) {
    try {
        oklchStr = oklchStr.trim();
        if (oklchStr.startsWith("#")) {
            const hex = parseInt(oklchStr.slice(1), 16);
            return {
                r: ((hex >> 16) & 255) / 255,
                g: ((hex >> 8) & 255) / 255,
                b: (hex & 255) / 255
            };
        }
        const match = oklchStr.match(/oklch\(\s*([\d\.]+%?)\s+([\d\.]+)\s+([\d\.]+)/);
        if (!match) return { r: 0.5, g: 0.5, b: 0.5 };
        let l = match[1].endsWith("%") ? parseFloat(match[1]) / 100 : parseFloat(match[1]);
        const c = parseFloat(match[2]);
        if (c < 0.05) return { r: l, g: l, b: l };
        return { r: l, g: l, b: l };
    } catch (e) {
        return { r: 1, g: 0, b: 0 };
    }
}

function parseColor(colorStr) {
    colorStr = colorStr.trim();
    if (colorStr.startsWith("#")) {
        const hex = parseInt(colorStr.slice(1), 16);
        return { r: ((hex >> 16) & 255) / 255, g: ((hex >> 8) & 255) / 255, b: (hex & 255) / 255 };
    }
    if (colorStr.startsWith("oklch")) return oklchToRgb(colorStr);
    return { r: 0.5, g: 0.5, b: 0.5 };
}

async function run() {
    try {
        notify("⏳ Syncing design tokens...");
        
        const colors = {
    "radius": "0.625rem",
    "background": "oklch(1 0 0)",
    "foreground": "oklch(0.145 0 0)",
    "card": "oklch(1 0 0)",
    "card-foreground": "oklch(0.145 0 0)",
    "popover": "oklch(1 0 0)",
    "popover-foreground": "oklch(0.145 0 0)",
    "primary": "oklch(0.205 0 0)",
    "primary-foreground": "oklch(0.985 0 0)",
    "secondary": "oklch(0.97 0 0)",
    "secondary-foreground": "oklch(0.205 0 0)",
    "muted": "oklch(0.97 0 0)",
    "muted-foreground": "oklch(0.556 0 0)",
    "accent": "oklch(0.97 0 0)",
    "accent-foreground": "oklch(0.205 0 0)",
    "destructive": "oklch(0.577 0.245 27.325)",
    "border": "oklch(0.922 0 0)",
    "input": "oklch(0.922 0 0)",
    "ring": "oklch(0.708 0 0)",
    "chart-1": "oklch(0.646 0.222 41.116)",
    "chart-2": "oklch(0.6 0.118 184.704)",
    "chart-3": "oklch(0.398 0.07 227.392)",
    "chart-4": "oklch(0.828 0.189 84.429)",
    "chart-5": "oklch(0.769 0.188 70.08)",
    "sidebar": "oklch(0.985 0 0)",
    "sidebar-foreground": "oklch(0.145 0 0)",
    "sidebar-primary": "oklch(0.205 0 0)",
    "sidebar-primary-foreground": "oklch(0.985 0 0)",
    "sidebar-accent": "oklch(0.97 0 0)",
    "sidebar-accent-foreground": "oklch(0.205 0 0)",
    "sidebar-border": "oklch(0.922 0 0)",
    "sidebar-ring": "oklch(0.708 0 0)",
    "dark-background": "oklch(0.145 0 0)",
    "dark-foreground": "oklch(0.985 0 0)",
    "dark-card": "oklch(0.205 0 0)",
    "dark-card-foreground": "oklch(0.985 0 0)",
    "dark-popover": "oklch(0.205 0 0)",
    "dark-popover-foreground": "oklch(0.985 0 0)",
    "dark-primary": "oklch(0.922 0 0)",
    "dark-primary-foreground": "oklch(0.205 0 0)",
    "dark-secondary": "oklch(0.269 0 0)",
    "dark-secondary-foreground": "oklch(0.985 0 0)",
    "dark-muted": "oklch(0.269 0 0)",
    "dark-muted-foreground": "oklch(0.708 0 0)",
    "dark-accent": "oklch(0.269 0 0)",
    "dark-accent-foreground": "oklch(0.985 0 0)",
    "dark-destructive": "oklch(0.704 0.191 22.216)",
    "dark-border": "oklch(1 0 0 / 10%)",
    "dark-input": "oklch(1 0 0 / 15%)",
    "dark-ring": "oklch(0.556 0 0)",
    "dark-chart-1": "oklch(0.488 0.243 264.376)",
    "dark-chart-2": "oklch(0.696 0.17 162.48)",
    "dark-chart-3": "oklch(0.769 0.188 70.08)",
    "dark-chart-4": "oklch(0.627 0.265 303.9)",
    "dark-chart-5": "oklch(0.645 0.246 16.439)",
    "dark-sidebar": "oklch(0.205 0 0)",
    "dark-sidebar-foreground": "oklch(0.985 0 0)",
    "dark-sidebar-primary": "oklch(0.488 0.243 264.376)",
    "dark-sidebar-primary-foreground": "oklch(0.985 0 0)",
    "dark-sidebar-accent": "oklch(0.269 0 0)",
    "dark-sidebar-accent-foreground": "oklch(0.985 0 0)",
    "dark-sidebar-border": "oklch(1 0 0 / 10%)",
    "dark-sidebar-ring": "oklch(0.556 0 0)"
};
        
        await figma.loadFontAsync({ family: "Inter", style: "Regular" });
        await figma.loadFontAsync({ family: "Inter", style: "Bold" });
        
        const frame = figma.createFrame();
        frame.name = "Design System (Synced from Code)";
        frame.resize(900, 2000);
        frame.fills = [{type: 'SOLID', color: {r: 0.95, g: 0.95, b: 0.96}}];
        
        const title = figma.createText();
        title.characters = "Design Tokens";
        title.fontSize = 32;
        title.x = 40;
        title.y = 40;
        frame.appendChild(title);
        
        const subTitle = figma.createText();
        subTitle.characters = "Synced from code - " + new Date().toLocaleDateString();
        subTitle.fontSize = 14;
        subTitle.x = 40;
        subTitle.y = 80;
        subTitle.opacity = 0.6;
        frame.appendChild(subTitle);
        
        let y = 140;
        let x = 40;
        const itemHeight = 70;
        const colWidth = 280;
        
        for (const [name, value] of Object.entries(colors)) {
            const styleName = CONFIG.stylePrefix + name.replace(/-/g, "/");
            let paintStyle = figma.getLocalPaintStyles().find(s => s.name === styleName);
            
            if (!paintStyle) {
                paintStyle = figma.createPaintStyle();
                paintStyle.name = styleName;
            }
            
            const rgb = parseColor(value);
            paintStyle.paints = [{ type: 'SOLID', color: rgb }];
            paintStyle.description = `Source: code | Value: ${value}`;
            
            const group = figma.createGroup();
            group.name = name;
            
            const swatch = figma.createRectangle();
            swatch.resize(50, 50);
            swatch.cornerRadius = 8;
            swatch.fillStyleId = paintStyle.id;
            swatch.x = 0;
            swatch.y = 0;
            group.appendChild(swatch);
            
            const nameLabel = figma.createText();
            nameLabel.characters = name;
            nameLabel.fontSize = 14;
            nameLabel.fontName = { family: "Inter", style: "Bold" };
            nameLabel.x = 65;
            nameLabel.y = 5;
            group.appendChild(nameLabel);
            
            const valueLabel = figma.createText();
            valueLabel.characters = value;
            valueLabel.fontSize = 12;
            valueLabel.opacity = 0.6;
            valueLabel.x = 65;
            valueLabel.y = 25;
            group.appendChild(valueLabel);
            
            group.x = x;
            group.y = y;
            frame.appendChild(group);
            
            y += itemHeight;
            if (y > 1800) {
                y = 140;
                x += colWidth;
            }
        }
        
        frame.resize(x + colWidth, 2000);
        figma.viewport.scrollAndZoomIntoView([frame]);
        notify(`✅ Synced ${Object.keys(colors).length} colors to Figma`);
        
    } catch (err) {
        console.error(err);
        notify("❌ Error: " + err.message);
    } finally {
        // figma.closePlugin();
    }
}

run();
