import os
import re
import json
import requests
from typing import Dict, Any, Optional, List
from dataclasses import dataclass


@dataclass
class FigmaConfig:
    token: str
    file_key: str
    base_url: str = "https://api.figma.com/v1"


class ColorConverter:
    @staticmethod
    def hex_to_rgb(hex_color: str) -> Dict[str, float]:
        hex_color = hex_color.lstrip("#")
        if len(hex_color) == 3:
            hex_color = "".join([c * 2 for c in hex_color])
        r = int(hex_color[0:2], 16) / 255.0
        g = int(hex_color[2:4], 16) / 255.0
        b = int(hex_color[4:6], 16) / 255.0
        return {"r": r, "g": g, "b": b}

    @staticmethod
    def oklch_to_rgb(oklch_str: str) -> Dict[str, float]:
        try:
            oklch_str = oklch_str.strip()
            if oklch_str.startswith("#"):
                return ColorConverter.hex_to_rgb(oklch_str)

            match = re.match(
                r"oklch\(\s*([\d\.]+%?)\s+([\d\.]+)\s+([\d\.]+)", oklch_str
            )
            if not match:
                return {"r": 0, "g": 0, "b": 0}

            l_str, c, h = match.groups()
            l = (
                float(l_str.rstrip("%")) / 100.0
                if l_str.endswith("%")
                else float(l_str)
            )

            if c < 0.05:
                return {"r": l, "g": l, "b": l}

            return {"r": l, "g": l, "b": l}
        except Exception:
            return {"r": 0, "g": 0, "b": 0}

    @staticmethod
    def parse_color(color_str: str) -> Dict[str, float]:
        color_str = color_str.strip()
        if color_str.startswith("#"):
            return ColorConverter.hex_to_rgb(color_str)
        elif color_str.startswith("oklch"):
            return ColorConverter.oklch_to_rgb(color_str)
        elif color_str.startswith("rgb"):
            match = re.search(r"(\d+)\s*,\s*(\d+)\s*,\s*(\d+)", color_str)
            if match:
                r, g, b = [int(x) / 255.0 for x in match.groups()]
                return {"r": r, "g": g, "b": b}
        return {"r": 0, "g": 0, "b": 0}


class FigmaSyncService:
    def __init__(self, token: Optional[str] = None, file_key: Optional[str] = None):
        self.token = token or os.getenv("FIGMA_ACCESS_TOKEN")
        self.file_key = file_key or os.getenv("FIGMA_FILE_KEY")
        if not self.token or not self.file_key:
            raise ValueError("FIGMA_ACCESS_TOKEN and FIGMA_FILE_KEY must be set")
        self.config = FigmaConfig(
            token=self.token,
            file_key=self.file_key,
            base_url="https://api.figma.com/v1",
        )
        self.headers = {"X-Figma-Token": self.token}

    def get_file_info(self) -> Dict[str, Any]:
        url = f"{self.config.base_url}/files/{self.config.file_key}"
        resp = requests.get(url, headers=self.headers)
        if resp.status_code != 200:
            raise Exception(f"Failed to fetch file: {resp.status_code}")
        return resp.json()

    def get_local_styles(self) -> Dict[str, Any]:
        url = f"{self.config.base_url}/files/{self.config.file_key}/styles"
        resp = requests.get(url, headers=self.headers)
        if resp.status_code != 200:
            raise Exception(f"Failed to fetch styles: {resp.status_code}")
        return resp.json()

    def parse_css_variables(self, css_content: str) -> Dict[str, str]:
        variables = {}
        root_match = re.search(r":root\s*{(.*?)}", css_content, re.DOTALL)
        dark_match = re.search(r".dark\s*{(.*?)}", css_content, re.DOTALL)

        for match in [root_match, dark_match]:
            if match:
                prefix = "dark-" if match == dark_match else ""
                for line in match.group(1).splitlines():
                    line = line.strip()
                    if line.startswith("--") and ":" in line:
                        key, val = line.split(":", 1)
                        var_name = prefix + key.strip().lstrip("-")
                        variables[var_name] = val.strip().rstrip(";")
        return variables

    def generate_plugin_script(
        self,
        colors: Dict[str, str],
        file_name: str = "Design System (Synced from Code)",
    ) -> str:
        colors_json = json.dumps(colors, indent=4)

        js_code = f"""// Figma Plugin Script - Generated by AI Design Workflow
// Run this in Figma: Plugins -> Development -> New Plugin -> Paste code

const CONFIG = {{
    fileKey: "{self.config.file_key}",
    token: "{self.token[:20]}...",
    stylePrefix: "Design Tokens/"
}};

function notify(msg) {{
    console.log(msg);
    figma.notify(msg);
}}

function oklchToRgb(oklchStr) {{
    try {{
        oklchStr = oklchStr.trim();
        if (oklchStr.startsWith("#")) {{
            const hex = parseInt(oklchStr.slice(1), 16);
            return {{
                r: ((hex >> 16) & 255) / 255,
                g: ((hex >> 8) & 255) / 255,
                b: (hex & 255) / 255
            }};
        }}
        const match = oklchStr.match(/oklch\\(\\s*([\\d\\.]+%?)\\s+([\\d\\.]+)\\s+([\\d\\.]+)/);
        if (!match) return {{ r: 0.5, g: 0.5, b: 0.5 }};
        let l = match[1].endsWith("%") ? parseFloat(match[1]) / 100 : parseFloat(match[1]);
        const c = parseFloat(match[2]);
        if (c < 0.05) return {{ r: l, g: l, b: l }};
        return {{ r: l, g: l, b: l }};
    }} catch (e) {{
        return {{ r: 1, g: 0, b: 0 }};
    }}
}}

function parseColor(colorStr) {{
    colorStr = colorStr.trim();
    if (colorStr.startsWith("#")) {{
        const hex = parseInt(colorStr.slice(1), 16);
        return {{ r: ((hex >> 16) & 255) / 255, g: ((hex >> 8) & 255) / 255, b: (hex & 255) / 255 }};
    }}
    if (colorStr.startsWith("oklch")) return oklchToRgb(colorStr);
    return {{ r: 0.5, g: 0.5, b: 0.5 }};
}}

async function run() {{
    try {{
        notify("⏳ Syncing design tokens...");
        
        const colors = {colors_json};
        
        await figma.loadFontAsync({{ family: "Inter", style: "Regular" }});
        await figma.loadFontAsync({{ family: "Inter", style: "Bold" }});
        
        const frame = figma.createFrame();
        frame.name = "{file_name}";
        frame.resize(900, 2000);
        frame.fills = [{{type: 'SOLID', color: {{r: 0.95, g: 0.95, b: 0.96}}}}];
        
        const title = figma.createText();
        title.characters = "Design Tokens";
        title.fontSize = 32;
        title.x = 40;
        title.y = 40;
        frame.appendChild(title);
        
        const subTitle = figma.createText();
        subTitle.characters = "Synced from code - " + new Date().toLocaleDateString();
        subTitle.fontSize = 14;
        subTitle.x = 40;
        subTitle.y = 80;
        subTitle.opacity = 0.6;
        frame.appendChild(subTitle);
        
        let y = 140;
        let x = 40;
        const itemHeight = 70;
        const colWidth = 280;
        
        for (const [name, value] of Object.entries(colors)) {{
            const styleName = CONFIG.stylePrefix + name.replace(/-/g, "/");
            let paintStyle = figma.getLocalPaintStyles().find(s => s.name === styleName);
            
            if (!paintStyle) {{
                paintStyle = figma.createPaintStyle();
                paintStyle.name = styleName;
            }}
            
            const rgb = parseColor(value);
            paintStyle.paints = [{{ type: 'SOLID', color: rgb }}];
            paintStyle.description = `Source: code | Value: ${{value}}`;
            
            const group = figma.createGroup();
            group.name = name;
            
            const swatch = figma.createRectangle();
            swatch.resize(50, 50);
            swatch.cornerRadius = 8;
            swatch.fillStyleId = paintStyle.id;
            swatch.x = 0;
            swatch.y = 0;
            group.appendChild(swatch);
            
            const nameLabel = figma.createText();
            nameLabel.characters = name;
            nameLabel.fontSize = 14;
            nameLabel.fontName = {{ family: "Inter", style: "Bold" }};
            nameLabel.x = 65;
            nameLabel.y = 5;
            group.appendChild(nameLabel);
            
            const valueLabel = figma.createText();
            valueLabel.characters = value;
            valueLabel.fontSize = 12;
            valueLabel.opacity = 0.6;
            valueLabel.x = 65;
            valueLabel.y = 25;
            group.appendChild(valueLabel);
            
            group.x = x;
            group.y = y;
            frame.appendChild(group);
            
            y += itemHeight;
            if (y > 1800) {{
                y = 140;
                x += colWidth;
            }}
        }}
        
        frame.resize(x + colWidth, 2000);
        figma.viewport.scrollAndZoomIntoView([frame]);
        notify(`✅ Synced ${{Object.keys(colors).length}} colors to Figma`);
        
    }} catch (err) {{
        console.error(err);
        notify("❌ Error: " + err.message);
    }} finally {{
        // figma.closePlugin();
    }}
}}

run();
"""
        return js_code


def load_css_file(path: str = "web-ui/app/globals.css") -> str:
    if not os.path.exists(path):
        raise FileNotFoundError(f"CSS file not found: {path}")
    with open(path, "r") as f:
        return f.read()


def load_tokens_file(path: str = "web-ui/design-tokens.json") -> Dict[str, Any]:
    if not os.path.exists(path):
        return {}
    with open(path, "r") as f:
        return json.load(f)
